### ISSUE TITLE
It is currently not responsive. Do we have any plans to upgrade this to support smaller viewports ?

### ISSUE THREAD

**Issue by faran4engg** [p32929/p32929.github.io#1]

**Comment by p32929** [comment]
![Screenshot (23)](https://user-images.githubusercontent.com/6418354/87846813-93795800-c8f4-11ea-98d4-93514b52793e.png)
I've tried using the portfolio in so many devices and height/widths. So far, it is FULLY RESPONSIVE and never really had any problem. Which device did you test it & found unresponsive?

**Comment by faran4engg** [comment]
I tested in chrome dev tools itself !
![portfolio-issue](https://user-images.githubusercontent.com/24570234/87847183-4b4b3d00-c8d6-11ea-942a-f74320645139.gif)

**Comment by p32929** [comment]
Oww, That's a very small screen. I just ignored those viewports because its hard to find that smaller screen phones nowadays :) 
But if you want to make some changes, pull requests are most welcome :)

**Comment by p32929** [comment]
Oww, 320X413, that's a very small screen & its quite hard to find that small screen devices nowadays. Most phones nowadays has great screen with a good resolution. & Smaller devices like 320X413 or similar devices don't even support JavaScript natively. So, I just didn't think, it would be important to consider those smaller screens. 

But if you want to fix them, feel free to. Pull requests are most welcome... :)

**Comment by p32929** [comment]
![Screenshot (29)](https://user-images.githubusercontent.com/6418354/88067326-ac059e80-cb90-11ea-8baf-20ba2a25ad25.png)

I just found an EASY fix for the problem. So, just updated the codes. Now it should show properly in smaller devices too... :)
