### ISSUE TITLE
Add Code of Conduct and Contributing.md file in repo

### ISSUE THREAD

**Issue by Shaishav0507** [p32929/p32929.github.io#10]
Hey @p32929 
I would like to contribute to this project by adding code of conduct and contributing.md file in the repo.
If you would like to add them to your repo, I will do that.
Thanks

**Comment by p32929** [comment]
Sure! Any contribution is most welcome :)

**Comment by p32929** [comment]
Would you be kind enough to write it here first?

**Comment by Shaishav0507** [comment]
Sure

**Comment by Shaishav0507** [comment]
This is the script for Code of conduct
# Contributor Covenant Code of Conduct## Our PledgeWe as members, contributors, and leaders pledge to make participation in ourcommunity a harassment-free experience for everyone, regardless of age, bodysize, visible or invisible disability, ethnicity, sex characteristics, genderidentity and expression, level of experience, education, socio-economic status,nationality, personal appearance, race, religion, or sexual identityand orientation.We pledge to act and interact in ways that contribute to an open, welcoming,diverse, inclusive, and healthy community.## Our StandardsExamples of behavior that contributes to a positive environment for ourcommunity include:* Demonstrating empathy and kindness toward other people* Being respectful of differing opinions, viewpoints, and experiences* Giving and gracefully accepting constructive feedback* Accepting responsibility and apologizing to those affected by our mistakes,  and learning from the experience* Focusing on what is best not just for us as individuals, but for the  overall communityExamples of unacceptable behavior include:* The use of sexualized language or imagery, and sexual attention or  advances of any kind* Trolling, insulting or derogatory comments, and personal or political attacks* Public or private harassment* Publishing others' private information, such as a physical or email  address, without their explicit permission* Other conduct which could reasonably be considered inappropriate in a  professional setting## Enforcement ResponsibilitiesProject maintainers and event organizers are responsible for clarifying and enforcing our standards ofacceptable behavior and will take appropriate and fair corrective action inresponse to any behavior that they deem inappropriate, threatening, offensive,or harmful.Project maintainers and event organizers have the right and responsibility to remove, edit, or rejectcomments, commits, code, wiki edits, issues, and other contributions that arenot aligned to this Code of Conduct, and will communicate reasons for moderationdecisions when appropriate.## ScopeThis Code of Conduct applies within all community spaces, and also applies whenan individual is officially representing the community in public spaces.Examples of representing our community include using an official e-mail address,posting via an official social media account, or acting as an appointedrepresentative at an online or offline event.## EnforcementInstances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting the project team at . All complaints will be reviewed and investigated and will result in a response that is deemed necessary and appropriate to the circumstances. The project team is obligated to maintain confidentiality with regard to the reporter of an incident. Further details of specific enforcement policies may be posted separately.Project maintainers who do not follow or enforce the Code of Conduct in good faith may face temporary or permanent repercussions as determined by other members of the project's leadership.## Enforcement GuidelinesProject maintainers and event organizers will follow these Community Impact Guidelines in determiningthe consequences for any action they deem in violation of this Code of Conduct:### 1. Correction**Community Impact**: Use of inappropriate language or other behavior deemedunprofessional or unwelcome in the community.**Consequence**: A private, written warning from community leaders, providingclarity around the nature of the violation and an explanation of why thebehavior was inappropriate. A public apology may be requested.### 2. Warning**Community Impact**: A violation through a single incident or seriesof actions.**Consequence**: A warning with consequences for continued behavior. Nointeraction with the people involved, including unsolicited interaction withthose enforcing the Code of Conduct, for a specified period of time. Thisincludes avoiding interactions in community spaces as well as external channelslike social media. Violating these terms may lead to a temporary orpermanent ban.### 3. Temporary Ban**Community Impact**: A serious violation of community standards, includingsustained inappropriate behavior.**Consequence**: A temporary ban from any sort of interaction or publiccommunication with the community for a specified period of time. No public orprivate interaction with the people involved, including unsolicited interactionwith those enforcing the Code of Conduct, is allowed during this period.Violating these terms may lead to a permanent ban.### 4. Permanent Ban**Community Impact**: Demonstrating a pattern of violation of communitystandards, including sustained inappropriate behavior,  harassment of anindividual, or aggression toward or disparagement of classes of individuals.**Consequence**: A permanent ban from any sort of public interaction withinthe community.## AttributionThis Code of Conduct is adapted from the [Contributor Covenant][homepage],version 2.0, available athttps://www.contributor-covenant.org/version/2/0/code_of_conduct.html.Community Impact Guidelines were inspired by [Mozilla's code of conductenforcement ladder](https://github.com/mozilla/diversity).[homepage]: https://www.contributor-covenant.orgFor answers to common questions about this code of conduct, see the FAQ athttps://www.contributor-covenant.org/faq. Translations are available athttps://www.contributor-covenant.org/translations.

**Comment by Shaishav0507** [comment]
Same goes with contribution guide lines

**Comment by Shaishav0507** [comment]
Should I go ahead or not ? @p32929

**Comment by p32929** [comment]
I'm kinda confused as the texts are unformatted. Can you comment how its gonna look if the file is opened? I mean, comment here with a proper format? Thanks in advance...

**Comment by Shaishav0507** [comment]
What if I do the changes and then you can review them.
If you like you can merge them or close it.
It its fine with you.

**Comment by Shaishav0507** [comment]
You would like the changes

**Comment by p32929** [comment]
Closing this issue, as a pull request has been made by @Shaishav0507 about this. 
Thanks to @Shaishav0507 btw
