### ISSUE TITLE
Site becomes fixed after opening

### ISSUE THREAD

**Issue by bdlowery** [p32929/p32929.github.io#5]
opened website in chrome at 1682px width:
![image](https://user-images.githubusercontent.com/16507857/108649914-283bc980-7473-11eb-9ded-9b861687e5b2.png)

full screened my chrome window to 1920px width after opening site:
![image](https://user-images.githubusercontent.com/16507857/108649943-3558b880-7473-11eb-9411-725acc2718db.png)

**Comment by p32929** [comment]
Thanks for writing the issue. I actually don't have a big display monitor. So, I just need to ask you: which one looks better? The first image or the second?

**Comment by p32929** [comment]
To be honest, that is the actual behavior. MaterialUI doesn't provide a whole lot of screen size breakpoints. There's only two breakpoints between 1682 and 1920, which are LG and XL. So, I just coded it with the default breakpoints. 

Thanks for writing the issue btw. But it seems to be working the way I intended it to work.

**Comment by bdlowery** [comment]
You can make your own breakpoints in materialUI and make the website responsive.

**Comment by p32929** [comment]
If you'd like to fix the issue, pull requests are most welcome :)
